name: Update
"on":
  push:
    branches:
      - renovate/octokit-openapi-webhooks-*
      - renovate/octokit-monorepo
      - renovate/major-octokit-monorepo
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: lts/*
      - run: npm ci
      - run: npm run -w packages/webhooks.js generate-types
      - name: create pull request
        uses: gr2m/create-or-update-pull-request-action@v1.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: 🚧 🤖📯 Webhooks changed
          body:
            An update to the OpenAPI spec has been detected, and required updates to
            your code. Please review the changes and merge this PR if everything
            looks good.
          branch: ${{ github.ref }}
          commit-message: "WIP: Webhooks changed - please review"
